steps:
- task: NodeTool@0
  inputs:
    versionSpec: 12.x

- task: UsePythonVersion@0
  inputs:
    versionSpec: '2.7'
    architecture: 'x64'

- script: node scripts/cibuild.js --target-cpu=$(TARGET_CPU)
  displayName: Build and test
  condition: ne(variables['Agent.OS'], 'Linux')

- script: xvfb-run node scripts/cibuild.js --target-cpu=$(TARGET_CPU)
  displayName: Build and test with xvfb
  condition: eq(variables['Agent.OS'], 'Linux')

- bash: |
    VERSION=`git describe --always --tags`
    echo "##vso[task.setvariable variable=Version;isOutput=true]$VERSION"
  displayName: Get Yue version
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  name: Yue

- task: GithubRelease@0
  displayName: Create GitHub Release
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  inputs:
    gitHubConnection: GitHub Yue
    repositoryName: yue/yue
    action: Edit
    tagSource: auto
    tag: $(Yue.Version)
    title: Yue $(Yue.Version)
    releaseNotesSource: input
    releaseNotes: (placeholder)
    assets: 'out/Dist/*.zip'
    assetUploadMode: replace
    isDraft: true
    addChangelog: false
